worker_processes auto;

events {
    worker_connections 4096;
}

http {
    upstream hybridroute {
        server hybridroute:8080;
        keepalive 128;
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 1m;
        client_body_timeout 10s;
        keepalive_timeout 65s;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-HybridRoute-Route "";
            proxy_set_header X-HybridRoute-Score "";
            proxy_set_header X-HybridRoute-Mode "";
            proxy_set_header Connection "";
            proxy_pass http://hybridroute;
        }
    }
}
